public class Constants {

    public static int PLAYERS_NUM = 15,MATCHES_FOR_ROUND = 5;

    public static final String[] PLAYERS_FIRST_NAMES = {"Lionel",
           " Cristiano",
            "Neymar",
            "Kylian",
            "Mohamed",
            "Kevin",
            "Robert",
            "Harry",
            "Sergio",
            "Luka",
            "Eden",
            "Virgil",
            "Manuel",
            "Paulo",
            "Antoine",
            "Karim",
            "Luis",
            "Paul",
            "Marco",
            "Gareth",
            "Romelu",
            "David",
            "Sadio",
            "Toni",
            "Alisson",
            "Raheem",
            "Thomas",
            "Marcelo",
            "Thiago",
            "Pierre-Emerick"};

    public static final String[] PLAYERS_LAST_NAMES = {"Messi",
            "Ronaldo",
            "Jr",
            "Mbappé",
            "Salah",
            "Bruyne",
            "Lewandowski",
            "Kane",
            "Ramos",
            "Modrić",
            "Hazard",
            "Dijk",
            "Neuer",
            "Dybala",
            "Griezmann",
            "Benzema",
            "Suárez",
            "Pogba",
            "Reus",
            "Bale",
            "Lukaku",
            "De Gea",
            "Mané",
            "Kroos",
            "Becker",
            "Sterling",
            "Müller",
            "Vieira",
            "Alcântara",
            "Aubameyang"};
}
